# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import videos_pb2 as videos__pb2


class VideosStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVideos = channel.unary_stream(
                '/main.Videos/GetVideos',
                request_serializer=videos__pb2.VideoRequest.SerializeToString,
                response_deserializer=videos__pb2.Video.FromString,
                )


class VideosServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetVideos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideosServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVideos': grpc.unary_stream_rpc_method_handler(
                    servicer.GetVideos,
                    request_deserializer=videos__pb2.VideoRequest.FromString,
                    response_serializer=videos__pb2.Video.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'main.Videos', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Videos(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetVideos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/main.Videos/GetVideos',
            videos__pb2.VideoRequest.SerializeToString,
            videos__pb2.Video.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
