# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: videos.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvideos.proto\x12\x04main\"\x0e\n\x0cVideoRequest\"\x14\n\x05Video\x12\x0b\n\x03url\x18\x01 \x01(\t2:\n\x06Videos\x12\x30\n\tGetVideos\x12\x12.main.VideoRequest\x1a\x0b.main.Video\"\x00\x30\x01\x62\x06proto3')



_VIDEOREQUEST = DESCRIPTOR.message_types_by_name['VideoRequest']
_VIDEO = DESCRIPTOR.message_types_by_name['Video']
VideoRequest = _reflection.GeneratedProtocolMessageType('VideoRequest', (_message.Message,), {
  'DESCRIPTOR' : _VIDEOREQUEST,
  '__module__' : 'videos_pb2'
  # @@protoc_insertion_point(class_scope:main.VideoRequest)
  })
_sym_db.RegisterMessage(VideoRequest)

Video = _reflection.GeneratedProtocolMessageType('Video', (_message.Message,), {
  'DESCRIPTOR' : _VIDEO,
  '__module__' : 'videos_pb2'
  # @@protoc_insertion_point(class_scope:main.Video)
  })
_sym_db.RegisterMessage(Video)

_VIDEOS = DESCRIPTOR.services_by_name['Videos']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VIDEOREQUEST._serialized_start=22
  _VIDEOREQUEST._serialized_end=36
  _VIDEO._serialized_start=38
  _VIDEO._serialized_end=58
  _VIDEOS._serialized_start=60
  _VIDEOS._serialized_end=118
# @@protoc_insertion_point(module_scope)
