apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.main.name }}
  labels:
    {{- toYaml .Values.main.labels | nindent 4}}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      {{- toYaml .Values.main.labels | nindent 6}}
  template:
    metadata:
      labels:
        {{- toYaml .Values.main.labels | nindent 8}}
    spec:
      containers:
        {{- with .Values.main -}}
        {{range .containers}}
          - name: {{ .name }}
            image: {{.image }}
            imagePullPolicy: {{.pullPolicy}}
            env:  
            {{toYaml .env | nindent 14}}
            ports:
            {{ range .ports}}
              - name: {{.name}}
                containerPort: {{.containerPort}}
                {{if .protocol}}
                protocol: {{.protocol}}
                {{end}}
            {{end}}
            {{if .livenessProbe}}
            livenessProbe:
              httpGet:
                path: {{.livenessProbe.path}}
                port: {{.livenessProbe.port}}
            {{end}}
            {{if .readinessProbe}}
            readinessProbe:
              httpGet:
                path: {{.readinessProbe.path}}
                port: {{.readinessProbe.port}}
            {{end}}
            {{if .resources}}
            resources:
              {{- toYaml .resources | nindent 14 }}
            {{end}}
        {{end}}
        {{end}}

---

apiVersion: v1
kind: Service
metadata:
  name: {{.Values.main.service.name}}
  labels:
  {{- toYaml .Values.main.labels | nindent 4}}
spec:
  type: {{.Values.main.service.type}}
  ports: 
    {{- range .Values.main.service.ports}}
    - port: {{.port}}
      targetPort: {{.targetPort}}
      {{- if .protocol}}
      protocol: {{.protocol}}
      {{end -}}
      name: {{.name}}
    {{- end}}
  selector:
  {{- toYaml .Values.main.labels | nindent 4}}
  
