apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grpc-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{.Values.main.service.name}}
            port:
              {{with (index .Values.main.service.ports 0)}}
              number: {{.port}}
              {{end}}
    host:
