apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  # Example:
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | b64enc }}   
  POSTGRES_URL: {{ .Values.db.service.name | b64enc }}   