# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproducts.proto\x12\x04main\"\x10\n\x0eProductRequest\"5\n\x07Product\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x05\x32\x42\n\x08Products\x12\x36\n\x0bGetProducts\x12\x14.main.ProductRequest\x1a\r.main.Product\"\x00\x30\x01\x62\x06proto3')



_PRODUCTREQUEST = DESCRIPTOR.message_types_by_name['ProductRequest']
_PRODUCT = DESCRIPTOR.message_types_by_name['Product']
ProductRequest = _reflection.GeneratedProtocolMessageType('ProductRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTREQUEST,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:main.ProductRequest)
  })
_sym_db.RegisterMessage(ProductRequest)

Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCT,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:main.Product)
  })
_sym_db.RegisterMessage(Product)

_PRODUCTS = DESCRIPTOR.services_by_name['Products']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCTREQUEST._serialized_start=24
  _PRODUCTREQUEST._serialized_end=40
  _PRODUCT._serialized_start=42
  _PRODUCT._serialized_end=95
  _PRODUCTS._serialized_start=97
  _PRODUCTS._serialized_end=163
# @@protoc_insertion_point(module_scope)
