# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

main:
  name: "grpc-app"
  labels:
    app: app
  containers:
    - name: app
      image: utibeabasi6/grpc-app
      pullPolicy: IfNotPresent
      ports:
        - name: http
          containerPort: &main-port 5000
      resources:
      env:
        - name: VIDEOS_ADDR
          valueFrom:
            configMapKeyRef:
              name: microsvc-config
              key: VIDEOS_ADDR
        - name: PRODUCTS_ADDR
          valueFrom:
            configMapKeyRef:
              name: microsvc-config
              key: PRODUCTS_ADDR
        
  service:
    name: grpc-app-svc
    type: LoadBalancer
    ports:
      - name: http
        port: 5000
        targetPort: *main-port
        protocol: TCP
  
videos:
  name: "grpc-videos"
  labels:
    app: videos
  containers:
    - name: videos
      image: utibeabasi6/grpc-videos
      pullPolicy: IfNotPresent
      ports:
        - name: http
          containerPort: &videos-port 50052
      resources:
      env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: POSTGRES_URL
  service:
    name: grpc-videos-svc
    type: ClusterIP
    ports:
      - name: http
        port: 50052
        targetPort: *videos-port
        protocol: TCP
  

products:
  name: "grpc-products"
  labels:
    app: products
  containers:
    - name: products
      image: utibeabasi6/grpc-products
      pullPolicy: IfNotPresent
      ports:
        - name: http
          containerPort: &products-port 50051
      resources:
      env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: POSTGRES_URL

  service:
    name: grpc-products-svc
    type: ClusterIP
    ports:
      - name: http
        port: 50051
        targetPort: *products-port
        protocol: TCP

db:
  name: "grpc-db"
  labels:
    app: db
  containers:
    - name: db
      image: utibeabasi6/grpc-db
      pullPolicy: IfNotPresent
      ports:
        - name: http
          containerPort: &db-port 5432
      resources:
      volumes:
        - name: db-data
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: POSTGRES_PASSWORD
  volumeTemplates:
    - name: db-data
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi

  service:
    name: grpc-db-svc
    type: ClusterIP
    ports:
      - name: http
        port: 5432
        targetPort: *db-port
        protocol: TCP
  
secrets:
  POSTGRES_PASSWORD: password

config:
  PRODUCTS_ADDR: grpc-products-svc:50051
  VIDEOS_ADDR: grpc-videos-svc:50052